# Generated by Django 4.1.7 on 2023-03-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_images_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
    ]
